blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/YUuJ5XGK
    about: You can join our Discord.
  - name: Website
    url: https://opensource.tcetmumbai.in/
    about: Visit for more Information.